import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
size = 13.0
normal = { family = "JetBrains Mono" }
bold = { family = "JetBrains Mono" }
italic = { family = "JetBrains Mono" }
bold_italic = { family = "JetBrains Mono" }

[window]
option_as_alt = "Both"
