theme="gruvbox"

[editor]
line-number = "relative"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
";" = "command_mode"

[keys.insert]
j = { k = "normal_mode" }
