[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = ["ruff", "basedpyright"]
auto-format = true
formatter = {command = "bash", args = ["-c", "uv run ruff format - | uv run ruff check --fix -"]} 

