source ~/.zplug/init.zsh

zplug "plugins/git", from:oh-my-zsh
zplug "plugins/dotenv", from:oh-my-zsh
zplug "zsh-users/zsh-autosuggestions"
zplug "jeffreytse/zsh-vi-mode"
zplug "zsh-users/zsh-syntax-highlighting"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# Save history
HISTFILE=~/.zsh_history
HISTSIZE=1000000000
SAVEHIST=1000000000
setopt appendhistory

# Use Helix for psql editor
export export PSQL_EDITOR=hx

# Brew
export PATH=/opt/homebrew/bin:$PATH

# Fzy finder alias
alias vf='nvim $(find . -type f | fzy)'
alias f='ls -l $(find . -type f | fzy)'

# Gradle
alias gw=./gradlew

# Git related aliases
function gbpurge () {
  git branch --merged | grep -v "\*" | grep -v "master" | xargs -n 1 git branch -d
  git remote prune origin
}

eval "$(starship init zsh)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
